FROM node:14-alpine

WORKDIR /khoitran/src/app

ARG REACT_APP_SERVER_URL=http://localhost:5000
ENV REACT_APP_SERVER_URL=http://localhost:5000

COPY package*.json .
COPY ./public ./public
COPY ./src ./src
RUN npm ci
EXPOSE 3000
CMD ["npm", "start"]
